// <auto-generated>
// Generated by VFXAnimationEnumGenerator.cs — do NOT edit manually.
// Source: Assets/Resources/BaseAnimationVFX.controller
// Regenerate via:
//   • Tools → Crookedile → Regenerate VFX Animation Enum
//   • Right-click sprite sheet → Crookedile → Generate Anim from Sprite Sheet
//   • Save BaseAnimationVFX.controller (auto)
// </auto-generated>

using System.Collections.Generic;
using UnityEngine;

namespace Crookedile.Data.VFX
{
    /// <summary>
    /// Auto-generated enum of all states in <c>BaseAnimationVFX</c>.
    /// Use <see cref="VFXAnimationStateExtensions.ToStateName"/> to
    /// get the exact state name string for <c>Animator.Play()</c>.
    /// </summary>
    public enum VFXAnimationState
    {
        None = 0,
        Empty,
        FanfxYellowLightning,
        Fanfx2AbsorbLargeRed,
        Fanfx2ClawLargeBlack,
        Fanfx2EarthSpikesLargeBrown,
        Fanfx2FireSpellLargeRed,
        Fanfx2IceSpellLargeBlue,
        Fanfx2ShatterSmallBlack,
        Fireball,
    }

    /// <summary>Extension methods for <see cref="VFXAnimationState"/>.</summary>
    public static class VFXAnimationStateExtensions
    {
        private static readonly Dictionary<VFXAnimationState, string> StateNames =
            new Dictionary<VFXAnimationState, string>
        {
            { VFXAnimationState.None, string.Empty },
            { VFXAnimationState.Empty, "Empty" },
            { VFXAnimationState.FanfxYellowLightning, "fanfx_yellow_lightning" },
            { VFXAnimationState.Fanfx2AbsorbLargeRed, "fanfx2_absorb_large_red" },
            { VFXAnimationState.Fanfx2ClawLargeBlack, "fanfx2_claw_large_black" },
            { VFXAnimationState.Fanfx2EarthSpikesLargeBrown, "fanfx2_earth_spikes_large_brown" },
            { VFXAnimationState.Fanfx2FireSpellLargeRed, "fanfx2_fire_spell_large_red" },
            { VFXAnimationState.Fanfx2IceSpellLargeBlue, "fanfx2_ice_spell_large_blue" },
            { VFXAnimationState.Fanfx2ShatterSmallBlack, "fanfx2_shatter_small_black" },
            { VFXAnimationState.Fireball, "Fireball" },
        };

        /// <summary>
        /// Native pixel dimensions of the first sprite in each animation clip.
        /// Auto-populated at code-gen time by reading the clip's object-reference curves.
        /// States with no sprite keys (e.g. the Empty state) are omitted.
        /// Used by <see cref="Crookedile.UI.VFXAnimatedImage.PlayAnimation"/> to set the
        /// RectTransform size on activation so each animation displays at its correct dimensions.
        /// </summary>
        public static readonly Dictionary<string, Vector2> NativeSizes =
            new Dictionary<string, Vector2>
        {
            { "fanfx2_absorb_large_red", new Vector2(66.06451f, 66f) },
            { "fanfx2_claw_large_black", new Vector2(128f, 128f) },
            { "fanfx2_earth_spikes_large_brown", new Vector2(64f, 51f) },
            { "fanfx2_fire_spell_large_red", new Vector2(89.04347f, 89f) },
            { "fanfx2_ice_spell_large_blue", new Vector2(40.96f, 41f) },
            { "fanfx2_shatter_small_black", new Vector2(75.85185f, 75.20834f) },
            { "Fireball", new Vector2(51f, 128f) },
        };

        /// <summary>
        /// Returns the exact Animator state name string for <c>Animator.Play()</c>.
        /// Returns <see cref="string.Empty"/> for <c>VFXAnimationState.None</c>.
        /// </summary>
        public static string ToStateName(this VFXAnimationState state)
            => StateNames.TryGetValue(state, out var name) ? name : string.Empty;
    }
}
