using UnityEngine;
using Crookedile.Managers;

namespace Crookedile.Data.VFX
{
    /// <summary>
    /// Scriptable Event — describes a visual effect combining an optional Feel feedback
    /// (shake, punch, tween on an existing UI element) with an optional animation state
    /// played on the shared VFX prefab managed by <see cref="VFXManager"/>.
    ///
    /// The VFX system uses a single pooled prefab with one Animator Controller containing
    /// all animation clips. Each event selects which state to play via the
    /// <see cref="VFXAnimationState"/> enum — a dropdown of every state in the controller,
    /// auto-generated by <c>VFXAnimationEnumGenerator</c>.
    ///
    /// Either field can be left empty/None; the system no-ops cleanly for whichever is absent.
    ///
    /// Usage:
    ///   myVfxEvent.Play()               — no positional target
    ///   myVfxEvent.Play(rectTransform)  — spawns at a UI element's position
    ///   myVfxEvent.Play(worldPos)       — spawns at a world-space point (converted to canvas space)
    ///
    /// Create via:  Assets → Create → Crookedile → VFX → VFX Event
    /// </summary>
    [CreateAssetMenu(menuName = "Crookedile/VFX/VFX Event", fileName = "NewVFXEvent")]
    public class VFXEvent : ScriptableObject
    {
        [Header("Feel Feedback")]
        [Tooltip("ID of a named MMF_Player registered in FeedbackManager. Leave empty to skip Feel.\n" +
                 "Feel handles shake, scale-punch, and tween effects on existing UI elements.")]
        [SerializeField] private string _feedbackId;

        [Header("Animated Image")]
        [Tooltip("Animation state to play on the shared VFX prefab.\n" +
                 "States are auto-populated from BaseAnimationVFX.controller.\n" +
                 "Select None to skip the spawned animation effect.")]
        [SerializeField] private VFXAnimationState _animationState;

        [Tooltip("Canvas-space offset (in pixels) added to the target position after placement.")]
        [SerializeField] private Vector2 _offset = Vector2.zero;

        // ─── Properties ───────────────────────────────────────────────────────

        /// <summary>Named Feel player ID passed to <see cref="FeedbackManager.Play(string,Transform)"/>.</summary>
        public string FeedbackId => _feedbackId;

        /// <summary>
        /// The exact Animator state name string derived from <see cref="_animationState"/>.
        /// Returns <see cref="string.Empty"/> when <see cref="VFXAnimationState.None"/> is selected.
        /// Used internally by <see cref="VFXManager"/> — prefer setting <see cref="_animationState"/>
        /// via the Inspector dropdown rather than relying on this string directly.
        /// </summary>
        public string AnimationStateName => _animationState.ToStateName();

        /// <summary>Canvas-space pixel offset applied when positioning the animated image at the target.</summary>
        public Vector2 Offset => _offset;

        // ─── Public API ───────────────────────────────────────────────────────

        /// <summary>Play with no positional target. Feel plays at default position; animated image spawns at canvas center.</summary>
        public void Play() => VFXManager.Instance?.Play(this, (RectTransform)null);

        /// <summary>Play aimed at a UI element — animated image spawns at the element's canvas position.</summary>
        public void Play(RectTransform target) => VFXManager.Instance?.Play(this, target);

        /// <summary>Play at an explicit world-space position (converted to canvas space by VFXManager).</summary>
        public void Play(Vector3 worldPos) => VFXManager.Instance?.PlayAtWorld(this, worldPos);
    }
}
