using UnityEngine;

namespace Crookedile.Data.VFX
{
    /// <summary>
    /// Scriptable Event — describes an animation state to play on the shared VFX prefab.
    ///
    /// The VFX system uses a single pooled prefab with one Animator Controller containing
    /// all animation clips. Each event selects which state to play via the
    /// <see cref="VFXAnimationState"/> enum — a dropdown of every state in the controller,
    /// auto-generated by <c>VFXAnimationEnumGenerator</c>.
    ///
    /// Create via:  Assets → Create → Crookedile → VFX → VFX Event
    /// </summary>
    [CreateAssetMenu(menuName = "Crookedile/VFX/VFX Event", fileName = "NewVFXEvent")]
    public class VFXEvent : ScriptableObject
    {
        [Tooltip(
            "Animation state to play on the shared VFX prefab.\n"
                + "States are auto-populated from BaseAnimationVFX.controller.\n"
                + "Select None to skip the spawned animation effect."
        )]
        [SerializeField]
        private VFXAnimationState _animationState;

        [Tooltip("Canvas-space offset (in pixels) added to the target position after placement.")]
        [SerializeField]
        private Vector2 _offset = Vector2.zero;

        [Tooltip(
            "When card effects land, as a fraction of the clip length (0 = first frame, "
                + "1 = last frame). Drives the code-timed hit moment — no AnimationEvent "
                + "needs to be keyed in the clip."
        )]
        [Range(0f, 1f)]
        [SerializeField]
        private float _hitTimeNormalized = 0.5f;

        #region Properties
        /// <summary>
        /// The exact Animator state name string derived from <see cref="_animationState"/>.
        /// Returns <see cref="string.Empty"/> when <see cref="VFXAnimationState.None"/> is selected.
        /// </summary>
        public string AnimationStateName => _animationState.ToStateName();

        /// <summary>Canvas-space pixel offset applied when positioning the animated image at the target.</summary>
        public Vector2 Offset => _offset;

        /// <summary>Normalized (0–1) point in the clip at which effect callbacks fire.</summary>
        public float HitTimeNormalized => _hitTimeNormalized;

        #endregion
    }
}
