using System;
using System.Collections.Generic;
using Crookedile.Data.Cards;
using Crookedile.UI.Battle;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Crookedile.UI.Reward
{
    /// <summary>
    /// Post-battle card reward screen overlay.
    ///
    /// Displays a set of generated card offers (from
    /// <see cref="Crookedile.Data.Cards.CardDatabase.GenerateRewardOffer"/>) and lets the
    /// player pick one to permanently add to their run deck. Uses the shared
    /// <see cref="BattlePoolManager"/> to rent and return card buttons per-type, so each
    /// card type uses its own distinct prefab layout.
    ///
    /// Starts inactive. Call <see cref="Open"/> after a victory result and
    /// <see cref="Close"/> after the player has made their choice.
    ///
    /// <para>
    /// Scene setup: place as a child of the battle canvas (above the result panel in
    /// the hierarchy so it renders on top). Assign all serialised fields in the Inspector.
    /// </para>
    /// </summary>
    public class RewardScreen : MonoBehaviour
    {
        [Header("UI References")]
        [Tooltip("Header text shown at the top of the panel (e.g. 'Choose a Card').")]
        [SerializeField]
        private TMP_Text _titleText;

        [Tooltip("Parent Transform for the offered card buttons. Use a GridLayoutGroup.")]
        [SerializeField]
        private Transform _cardContainer;

        [Tooltip("Button that confirms the selection. Disabled until a card is chosen.")]
        [SerializeField]
        private Button _confirmButton;

        [Tooltip("Optional label on the confirm button ('Take Card').")]
        [SerializeField]
        private TMP_Text _confirmButtonLabel;

        [Tooltip("Button that skips the reward (calls onPick with null).")]
        [SerializeField]
        private Button _skipButton;

        #region Per-session state
        private readonly List<CardButton> _spawnedButtons = new List<CardButton>();
        private Action<CardData> _onPick;
        private CardData _selectedCard;
        private CardButton _selectedButton;

        #endregion

        #region Lifecycle
        private void Awake()
        {
            _confirmButton?.onClick.AddListener(OnConfirmClicked);
            _skipButton?.onClick.AddListener(OnSkipClicked);
            gameObject.SetActive(false);
        }

        #endregion

        #region Public API
        /// <summary>
        /// Opens the reward screen and displays the given card offers.
        /// </summary>
        /// <param name="offers">Cards the player can choose from (generated by CardDatabase).</param>
        /// <param name="onPick">
        /// Callback invoked with the chosen <see cref="CardData"/> when confirmed,
        /// or <c>null</c> if the player skips.
        /// </param>
        public void Open(List<CardData> offers, Action<CardData> onPick)
        {
            _onPick = onPick;
            _selectedCard = null;
            _selectedButton = null;

            if (_titleText != null)
                _titleText.text = "Choose a Card";
            if (_confirmButtonLabel != null)
                _confirmButtonLabel.text = "Take Card";
            if (_confirmButton != null)
                _confirmButton.interactable = false;

            ClearCards();
            SpawnOffers(offers);
            gameObject.SetActive(true);
        }

        /// <summary>
        /// Hides the reward screen and returns all card buttons to the pool.
        /// Called automatically when the player confirms or skips.
        /// </summary>
        public void Close()
        {
            ClearCards();
            _onPick = null;
            _selectedCard = null;
            _selectedButton = null;
            gameObject.SetActive(false);
        }

        #endregion

        #region Internal
        private void SpawnOffers(List<CardData> offers)
        {
            if (_cardContainer == null || offers == null)
                return;

            for (int i = 0; i < offers.Count; i++)
            {
                CardData card = offers[i];
                if (card == null)
                    continue;

                CardButton btn =
                    BattlePoolManager.Instance != null
                        ? BattlePoolManager.Instance.RentCard(card.CardType, _cardContainer)
                        : null;

                if (btn == null)
                {
                    Debug.LogWarning(
                        "[RewardScreen] BattlePoolManager.Instance is null or pool is empty. Card offer skipped."
                    );
                    continue;
                }

                int baseCost =
                    card.Costs != null && card.Costs.Count > 0 ? card.Costs[0].BaseAmount : 0;
                CardData captured = card;
                CardButton capturedBtn = btn;

                // int.MaxValue AP → always shown as affordable (no grey tint)
                btn.Initialize(
                    card,
                    i,
                    int.MaxValue,
                    baseCost,
                    onClick: () => SelectCard(captured, capturedBtn)
                );
                btn.SetPickerMode(true); // plain click-to-select; no hand hover-lift / drag-to-play

                // Force layout so SetBasePosition gets the real slot position, not (0,0)
                Canvas.ForceUpdateCanvases();
                btn.SetBasePosition(btn.transform.localPosition);

                _spawnedButtons.Add(btn);
            }
        }

        private void SelectCard(CardData card, CardButton btn)
        {
            // Deselect previous
            if (_selectedButton != null)
                _selectedButton.SetSelected(false);

            _selectedCard = card;
            _selectedButton = btn;
            btn.SetSelected(true);

            if (_confirmButton != null)
                _confirmButton.interactable = true;
        }

        private void OnConfirmClicked()
        {
            if (_selectedCard == null)
                return;

            CardData pick = _selectedCard;
            var callback = _onPick;
            Close();
            callback?.Invoke(pick);
        }

        private void OnSkipClicked()
        {
            var callback = _onPick;
            Close();
            callback?.Invoke(null);
        }

        private void ClearCards()
        {
            foreach (var btn in _spawnedButtons)
            {
                if (btn == null)
                    continue;
                if (BattlePoolManager.Instance != null)
                    BattlePoolManager.Instance.ReturnCard(btn);
                else
                    Destroy(btn.gameObject);
            }
            _spawnedButtons.Clear();
        }
    }
}
        #endregion
