namespace Crookedile.Data
{
    /// <summary>
    /// Card types for political negotiation.
    /// Pressure = persuasion / de-escalation, Rhetoric = aggressive framing,
    /// Policy = policy positions with a left/center/right lean that shifts demographics.
    /// </summary>
    public enum CardType
    {
        Pressure, // Green  - Persuasion, de-escalation, relationship building
        Rhetoric, // Red    - Aggressive framing, attacks, pressure tactics
        Policy, // Blue   - Policy positions; lean shifts all enemy hostility by demographic
        Status, // Purple - Temporary effect cards; some are unplayable
        Scandal, // Dark  - Manufactured controversy: unplayable, clogs the hand; the Celebrity exploits these
    }

    /// <summary>
    /// How a card-manipulation effect picks which card(s) it acts on.
    /// (Ordinals are serialized on effect assets — do not reorder.)
    /// </summary>
    public enum CardSelectionMode
    {
        PlayerChoice, // 0 — prompt the player via CardChoiceRequestedEvent
        RandomAny, // 1 — pick randomly from the whole pool
        RandomByType, // 2 — filter by a CardType, then pick randomly
    }

    /// <summary>
    /// Card rarity determines acquisition chance, power level, and visual frame.
    /// </summary>
    public enum CardRarity
    {
        Basic, // Basic cards from shops and starter decks
        Enhanced, // Enhanced effects, moderate acquisition difficulty
        Rare, // Powerful effects, harder to acquire
    }

    /// <summary>
    /// Player origin types. Each has unique starting deck and passive abilities.
    /// Simplified to 3 distinct archetypes.
    /// </summary>
    public enum OriginType
    {
        FaithLeader, // Religious leader - defensive, Confidence-focused
        NepoBaby, // Nepo baby - resource manipulation, Influence-focused
        Actor, // Celebrity/Actor - charismatic, versatile
    }

    /// <summary>
    /// Campaign/Overworld resources that persist across battles.
    /// Simplified to 3 core resources for cleaner gameplay.
    /// </summary>
    public enum CampaignResourceType
    {
        Funds, // ₱ - Campaign funds for buying cards, upgrades, etc.
        Heat, // H - Scandal meter (0-100), lose if too high
        Influence, // Political influence/power, win condition
    }

    /// <summary>
    /// Campaign/Overworld effect types for post-battle rewards and events.
    /// These affect the player's campaign state, not battle state.
    /// </summary>
    public enum CampaignEffectType
    {
        // Resource Gains/Losses (3 core resources only)
        GainFunds, // Gain ₱
        LoseFunds, // Lose ₱
        GainHeat, // Increase Heat (scandal)
        LoseHeat, // Decrease Heat
        GainInfluence, // Gain Influence (political power)
        LoseInfluence, // Lose Influence

        // Card Collection
        AddCardToDeck, // Permanently add card to deck
        RemoveCardFromDeck, // Permanently remove card from deck
        UpgradeCard, // Upgrade a card to + version
        TransformCard, // Transform one card into another

        // Progression
        UnlockLocation, // Unlock new map location
        UnlockCard, // Unlock card for future acquisition
        TriggerEvent, // Trigger a specific event
        AdvanceDay, // Skip to next day
    }

    public enum TargetType
    {
        Self,
        Opponent, // Single focused enemy (player) or the player (enemy)
        All, // Player + ALL living enemies
        Random, // Random single opponent
        AllOpponents, // Player card → all living enemies | Enemy card → the player
        AllAllies, // Enemy card → all living enemies  | Player card → self
        Adjacent, // Focused enemy + immediate row neighbours (player); the player (enemy)
        AllHostile, // Every living enemy with Hostility > 0 (the dissenters)
        AllReceptive, // Every living enemy with Hostility < 0 (the supporters)
        RandomReceptive, // One random living receptive enemy (e.g. Sway: convert a supporter)
    }

    /// <summary>
    /// Cost types for playing cards.
    /// NOTE: In battle, cards ONLY cost Action Points (or are free).
    /// Funds/Influence are meta resources used outside battle (shops, events, etc.)
    /// </summary>
    public enum CostType
    {
        None, // Free to play
        ActionPoints, // Battle resource - energy to play cards
        Patronage, // Nepo Baby's banked currency (generated by sacrificing cards). Persists across turns; spent on summons/installations.
    }

    public enum GamePhase
    {
        MainMenu,
        CharacterSelect,
        Campaign,
        Battle,
        Event,
        Shop,
        GameOver,
        Victory,
    }

    public enum BattlePhase
    {
        Setup,
        PlayerTurn,
        OpponentTurn,
        Victory,
        Defeat,
    }

    /// <summary>
    /// Political lean of a Policy card.
    /// Determines which demographics become more or less hostile when the card is played.
    /// None = not a Policy card (or Policy card with no lean effect).
    /// </summary>
    public enum PolicyLean
    {
        Left,
        Center,
        Right,
        None, // Default for Pressure/Rhetoric cards — no hostility shift applied
    }

    /// <summary>
    /// Socioeconomic class of an enemy demographic.
    /// Used for card targeting and thematic identification.
    /// </summary>
    public enum DemographicClass
    {
        Upper,
        Middle,
        Lower,
    }

    /// <summary>
    /// Political values of an enemy demographic.
    /// Determines how they react to Policy cards based on lean alignment.
    /// </summary>
    public enum DemographicValues
    {
        Progressive,
        Moderate,
        Traditional,
    }

    /// <summary>
    /// Determines where a BattleEffect reads its numeric amount at runtime.
    /// Used by passive and card effects to mirror values accumulated during resolution
    /// (e.g. heal for the damage you just dealt = LastDamageDealt).
    /// </summary>
    public enum EffectContextValue
    {
        FixedAmount, // 0 — use the inspector-authored value (shows fixed amount fields)
        LastDamageDealt, // 1 — ctx.LastDamageDealt  — e.g. lifesteal
        LastHealAmount, // 2 — ctx.LastHealAmount
        LastSupportGained, // 3 — ctx.LastSupportGained
        LastSupportLost, // 4 — ctx.LastSupportLost — e.g. bonus pressure equal to Support spent
        CurrentSupport, // 5 — session CurrentSupport at time of trigger
        CurrentHostility, // 6 — focused target.CurrentHostility at time of trigger
        None, // 7 — return 0; hides fixed amount fields (use when amount is irrelevant)
        HostileEnemyCount, // 8 — number of living enemies with Hostility > 0
        ReceptiveEnemyCount, // 9 — number of living enemies with Hostility < 0
        ConversionsThisTurn, // 10 — Faith Leader pacify conversions made this player turn (Sermon harvest)
        CurrentPatronage, // 11 — Nepo Baby's current banked Patronage
        ScandalsInHand, // 12 — Scandal cards currently clogging the player's hand (Celebrity Scandal line)
        ScandalsDrawnThisTurn, // 13 — Scandal cards drawn so far this turn (Celebrity on-draw payoffs)
        CurrentAttention, // 14 — Celebrity's banked Attention (spotlight resource)
    }
}
