#!/usr/bin/env python3
"""Keeps the docs formal: headers, the readme map, links, data files and the card-art workbook.

    python3 tools/check_docs.py          # check; exit 1 on errors
    python3 tools/check_docs.py --fix    # regenerate the readme map and sync the workbook, then check

Checks
  1. Every doc under docs/ (deprecated docs aside, their README included) opens with the standard
     header: Kind, Status, Updated, Summary, Source of truth, Related.
  2. The readme's documentation map (between the docs-map markers) matches the headers. --fix
     regenerates it.
  3. Every file under docs/ is linked from readme.md, directly or through a linked folder.
  4. Every relative link in readme.md, CLAUDE.md, AGENTS.md and the current docs resolves.
  5. docs/crookedile-card-art-prompts.xlsx has one row per card asset. The assets own the Card,
     Rarity and Type columns; the sheet owns Mechanic and Subject. --fix adds missing rows and
     corrects Rarity and Type; rows naming a card that no longer exists are reported, never deleted.
     Needs openpyxl (skipped with a warning without it).
Warnings (never fail): a doc changed in git after its Updated date; workbook rows with no subject.
"""

import datetime
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
README = ROOT / "readme.md"
WORKBOOK = DOCS / "crookedile-card-art-prompts.xlsx"
CARDS = ROOT / "Assets" / "Data" / "Cards"

KINDS = ["Design", "Systems", "Tracking", "Art", "Reference", "Index"]
STATUSES = ["Canonical", "Draft", "Proposal", "Built", "Partly built", "Living", "Stale", "Deprecated"]
KIND_TITLES = {
    "Design": "Design",
    "Systems": "Systems — code reference",
    "Tracking": "Planning & tracking",
    "Art": "Art",
    "Reference": "Generation prompts",
    "Index": "Deprecated",
}
MAP_START = "<!-- docs-map:start (generated by tools/check_docs.py --fix; edit the doc headers instead) -->"
MAP_END = "<!-- docs-map:end -->"

HEADER_RE = re.compile(
    r"^> \*\*Kind:\*\* (?P<kind>[^·\n]+?) · \*\*Status:\*\* (?P<status>[^·\n]+?) · \*\*Updated:\*\* (?P<updated>\S+)\n"
    r">\n> \*\*Summary:\*\* (?P<summary>.+)\n"
    r">\n> \*\*Source of truth:\*\* (?P<source>.+?) · \*\*Related:\*\* (?P<related>.+)$",
    re.M,
)
LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)|!\[[^\]]*\]\(([^)\s]+)\)")

# Card folder -> workbook tab. Status and curse cards share the Faith Leader tab, as they always have.
TABS = {"FaithLeader": "Faith Leader", "Status": "Faith Leader", "Curses": "Faith Leader", "Celebrity": "Celebrity", "NepoBaby": "Nepo Baby"}
CARD_TYPES = ["Pressure", "Rhetoric", "Policy", "Heckle", "Scandal"]
RARITIES = ["Basic", "Enhanced", "Rare"]
PROMPT_FORMULA = '=Settings!$B$2&" - "&E{r}&", "&Settings!$B$5&" "&Settings!$B$3&IF(Settings!$B$4<>""," --sref "&Settings!$B$4,"")'


def format_header(kind, status, updated, summary, source, related):
    return (
        f"> **Kind:** {kind} · **Status:** {status} · **Updated:** {updated}\n"
        f">\n> **Summary:** {summary}\n"
        f">\n> **Source of truth:** {source} · **Related:** {related}"
    )


def current_docs():
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(DOCS).as_posix()
        if rel.startswith("deprecated/") and rel != "deprecated/README.md":
            continue
        yield path


def git_date(path):
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=False,
        ).stdout.strip()
        return out or None
    except OSError:
        return None


class Report:
    def __init__(self):
        self.errors, self.warnings, self.fixed = [], [], []

    def error(self, msg):
        self.errors.append(msg)

    def warn(self, msg):
        self.warnings.append(msg)


def read_headers(report):
    headers = {}
    for path in current_docs():
        rel = path.relative_to(DOCS).as_posix()
        m = HEADER_RE.search(path.read_text(encoding="utf-8-sig"))
        if not m:
            report.error(f"docs/{rel}: no standard header (see tools/check_docs.py format_header)")
            continue
        h = {k: v.strip() for k, v in m.groupdict().items()}
        if h["kind"] not in KINDS:
            report.error(f"docs/{rel}: Kind '{h['kind']}' is not one of {KINDS}")
        if h["status"] not in STATUSES:
            report.error(f"docs/{rel}: Status '{h['status']}' is not one of {STATUSES}")
        try:
            datetime.date.fromisoformat(h["updated"])
        except ValueError:
            report.error(f"docs/{rel}: Updated '{h['updated']}' is not YYYY-MM-DD")
        else:
            changed = git_date(path)
            if changed and changed > h["updated"]:
                report.warn(f"docs/{rel}: changed in git on {changed}, header says Updated {h['updated']}")
        headers[rel] = h
    return headers


def rebase_links(text, doc_rel):
    """Rewrites a header's relative links (relative to the doc) to be relative to the repo root."""
    base = (DOCS / doc_rel).parent

    def fix(m):
        target = m.group(2)
        if re.match(r"^[a-z]+:|^#|^/", target):
            return m.group(0)
        path, _, anchor = target.partition("#")
        rel = os.path.relpath(os.path.normpath(base / path), ROOT).replace(os.sep, "/")
        return f"[{m.group(1)}]({rel}{'#' + anchor if anchor else ''})"

    return re.sub(r"\[([^\]]*)\]\(([^)\s]+)\)", fix, text)


def render_map(headers):
    lines = [MAP_START, ""]
    for kind in KINDS:
        rows = [(rel, h) for rel, h in headers.items() if h["kind"] == kind]
        if not rows:
            continue
        lines += [f"### {KIND_TITLES[kind]}", "", "| Doc | Status | Updated | What it covers | Source of truth |", "|---|---|---|---|---|"]
        for rel, h in rows:
            source = rebase_links(h["source"], rel)
            lines.append(f"| [`{rel}`](docs/{rel}) | {h['status']} | {h['updated']} | {h['summary']} | {source} |")
        lines.append("")
    lines.append(MAP_END)
    return "\n".join(lines)


def check_map(headers, report, fix):
    text = README.read_text(encoding="utf-8")
    start, end = text.find(MAP_START), text.find(MAP_END)
    if start < 0 or end < 0:
        report.error("readme.md: docs-map markers missing")
        return
    wanted = render_map(headers)
    current = text[start : end + len(MAP_END)]
    if current == wanted:
        return
    if fix:
        README.write_text(text[:start] + wanted + text[end + len(MAP_END) :], encoding="utf-8")
        report.fixed.append("readme.md: documentation map regenerated")
    else:
        report.error("readme.md: documentation map is out of date with the doc headers (run --fix)")


def links_in(path):
    text = path.read_text(encoding="utf-8-sig")
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    for m in LINK_RE.finditer(text):
        yield m.group(1) or m.group(2)


def resolve(base, target):
    if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I) or target.startswith("#"):
        return None
    path = target.split("#", 1)[0]
    if not path:
        return None
    from urllib.parse import unquote

    return (base / unquote(path)).resolve()


def check_links(report):
    files = [README, ROOT / "CLAUDE.md", ROOT / "AGENTS.md", *current_docs()]
    for f in files:
        if not f.exists():
            continue
        for target in links_in(f):
            p = resolve(f.parent, target)
            if p is not None and not p.exists():
                report.error(f"{f.relative_to(ROOT).as_posix()}: dead link {target}")


def check_coverage(report):
    linked = set()
    for target in links_in(README):
        p = resolve(ROOT, target)
        if p is not None:
            linked.add(p)
    for path in sorted(DOCS.rglob("*")):
        if path.is_dir() or path.name.endswith(".meta") or path.name.startswith("."):
            continue
        rel = path.relative_to(DOCS).as_posix()
        if rel.startswith("deprecated/"):
            continue  # covered by deprecated/README.md
        if not any(path == l or l in path.parents for l in linked):
            report.error(f"readme.md: docs/{rel} is not linked")


def card_assets():
    cards = []
    for f in sorted(CARDS.rglob("*.asset")):
        text = f.read_text(encoding="utf-8-sig")
        name = re.search(r"^  _cardName: (.*)$", text, re.M)
        if not name:
            continue

        def field(key):
            m = re.search(rf"^  {key}: (\d+)", text, re.M)
            return int(m.group(1)) if m else 0

        folder = f.relative_to(CARDS).parts[0]
        if folder == "Status":
            rarity = "Status"
        elif folder == "Curses":
            rarity = "Curse"
        elif field("_isGeneratedOnly"):
            rarity = "Token"
        else:
            rarity = RARITIES[field("_rarity")]
        cards.append(
            {
                "name": name.group(1).strip().strip("'\""),
                "tab": TABS.get(folder),
                "rarity": rarity,
                "type": CARD_TYPES[field("_cardType")],
                "path": f.relative_to(ROOT).as_posix(),
            }
        )
    return cards


def check_workbook(report, fix):
    try:
        import openpyxl
    except ImportError:
        report.warn("workbook check skipped: pip install openpyxl")
        return
    import copy

    wb = openpyxl.load_workbook(WORKBOOK)
    changed = False
    rows = {}
    for tab in sorted(set(TABS.values())):
        if tab not in wb.sheetnames:
            report.error(f"{WORKBOOK.name}: missing tab '{tab}'")
            continue
        ws = wb[tab]
        for r in range(2, ws.max_row + 1):
            name = ws.cell(r, 1).value
            if name:
                rows[str(name).strip()] = (ws, r)

    for card in card_assets():
        if card["tab"] is None:
            report.error(f"{card['path']}: card folder has no workbook tab (add it to TABS)")
            continue
        found = rows.pop(card["name"], None)
        if found is None:
            if not fix:
                report.error(f"{WORKBOOK.name}: no row for '{card['name']}' ({card['path']})")
                continue
            ws = wb[card["tab"]]
            r = ws.max_row + 1
            template = [ws.cell(2, c)._style for c in range(1, 7)]
            values = [card["name"], card["rarity"], card["type"], "", "", PROMPT_FORMULA.format(r=r)]
            for c, v in enumerate(values, 1):
                cell = ws.cell(r, c, v)
                cell._style = copy.copy(template[c - 1])
            if ws.auto_filter.ref:
                ws.auto_filter.ref = f"A1:F{r}"
            report.fixed.append(f"{WORKBOOK.name}: added '{card['name']}' to {card['tab']}")
            changed = True
            found = (ws, r)
        ws, r = found
        if ws.title != card["tab"]:
            report.error(f"{WORKBOOK.name}: '{card['name']}' is on tab {ws.title}, expected {card['tab']}")
        for col, key in ((2, "rarity"), (3, "type")):
            if ws.cell(r, col).value != card[key]:
                if fix:
                    ws.cell(r, col).value = card[key]
                    report.fixed.append(f"{WORKBOOK.name}: '{card['name']}' {key} -> {card[key]}")
                    changed = True
                else:
                    report.error(f"{WORKBOOK.name}: '{card['name']}' {key} is {ws.cell(r, col).value}, asset says {card[key]}")
        if not ws.cell(r, 5).value:
            report.warn(f"{WORKBOOK.name}: '{card['name']}' has no subject clause yet")

    for name, (ws, r) in rows.items():
        report.error(f"{WORKBOOK.name}: {ws.title} row {r} names '{name}', which no card asset has (rename or delete it)")

    if changed:
        wb.calculation.fullCalcOnLoad = True
        wb.save(WORKBOOK)


def main():
    fix = "--fix" in sys.argv
    report = Report()
    headers = read_headers(report)
    check_map(headers, report, fix)
    check_links(report)
    check_coverage(report)
    check_workbook(report, fix)

    for msg in report.fixed:
        print(f"fixed: {msg}")
    for msg in report.warnings:
        print(f"warning: {msg}")
    for msg in report.errors:
        print(f"error: {msg}")
    print(f"check_docs: {len(report.errors)} error(s), {len(report.warnings)} warning(s), {len(report.fixed)} fix(es)")
    return 1 if report.errors else 0


if __name__ == "__main__":
    sys.exit(main())
